### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by cameronelliott** [itskoko/prometheus-statuspage-pusher#1]
Most people cannot use this because there is no LICENSE file, would you accept a PR for the MIT license?
Thanks

**Comment by cameronelliott** [comment]
@discordianfish Hello, I have been working on this to add Statuspage component support, would you be interested in seeing PR's back here to possibly merge, or should I work on that stuff separatel? Still curious about the LICENSE, also.
Thank you

**Comment by discordianfish** [comment]
Looks like we forgot to add the license, fixed!

**Comment by discordianfish** [comment]
Sure, happy to see the PR. We'll need to see how it fits in here but happy to have a look!
