### ISSUE TITLE
resolving: x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by cameronelliott** [itskoko/prometheus-statuspage-pusher#2]
Just a quick question for you, when trying to use the Docker image, I got x509 errors, indicating that the go runtime couldn't find the certs for the https server of Statuspage.

I tried and tried to build a Docker image with the certs, but didn't succeed (pretty new to Docker), although I did succeed by passing the host's certifcate store into the image like this:
`docker run  -v /tmp/z:/queries.yaml -v '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt' ...`

Did you run into this issue?
Is that how you resolved the certificates issue? 
Did you resolve the certificates issue another way?

**Comment by juris** [comment]
Just use alpine or debian as a base image and add ca-certs package there:
```
...
FROM alpine:3.12

RUN apk add --no-cache ca-certificates
COPY --from=0 /psp/prometheus-statuspage-pusher /

ENTRYPOINT ["/prometheus-statuspage-pusher"]
```

**Comment by cameronelliott** [comment]
Thanks!
